### ISSUE TITLE
versioning.xml Documents are out of date

### ISSUE THREAD

**Issue by adamretter** [eXist-db/documentation#103] opened 2017-03-18 19:49 UTC
http://exist-db.org/exist/apps/doc/versioning.xml#D2.2.4.3

Also raised the question of where the documentation for an extension module be kept? And how that could be incorporated into the eXist-db website.

**Comment by joewiz** [comment] 2017-11-21 15:17
@adamretter Is this a dupe of #38? If so, perhaps the question about extension module documentation deserves its own issue.

**Comment by adamretter** [comment] 2017-11-21 19:48
@joewiz TBH it is so long since I opened the issue that I am not sure. A quick look makes me think that it is related rather than a duplicate.

**Comment by duncdrum** [comment] 2017-12-19 11:12
my 2ct: ignore the webpage, that should really not be something authors of extensions have to consider. 

if the extension module is present on default installs (but disabled) the documentation should be in this app, e.g. in `versioning.xml`. 

If users need to install an extension in a separate step, we should treat their documentation in a manner similar to how the fundocs app works. The author includes docbook documentation in the library/app and the documentation app generates a dynamic table, and displays it on local instances. This would require some changes to the app, but would provide a sustainable way moving forward.

**Closed** 2019-05-28 09:31 UTC
Labels: docs-outdated, more-information-needed
