### ISSUE TITLE
Dead links in menu item 'documentation'

### ISSUE THREAD

**Issue by lguariento** [eXist-db/documentation#455] opened 2020-03-21 01:01 UTC
Hello,

other than being a repetition, the menu item 'documentation' within the main menu item 'documentation' (at [this](http://exist-db.org/exist/apps/fundocs/index.html) page, for instance) brings up this error:

```
URI: | /exist/apps/doc/data/repo/listings/documentation.xml
-- | --
404
Document /db/apps/doc/data/repo/listings/documentation.xml not found
EXistServlet
```
Same for 'get support' under the same menu item.

Luca

![Screenshot_2020-03-21 XQuery Function Documentation](https://user-images.githubusercontent.com/10143842/77216043-8055a780-6b0f-11ea-9217-e1d9620e7d63.png)

**Comment by lguariento** [comment] 2020-03-21 01:05
PS: the XForms and the RestXQ demos are also dead.

**Comment by duncdrum** [comment] 2020-03-27 15:23
duplicate of https://github.com/eXist-db/function-documentation/issues/16

**Closed** 2020-04-07 14:31 UTC
Labels: bug
