### ISSUE TITLE
"HTTP method GET is not supported by this URL"

### ISSUE THREAD

**Issue by lguariento** [eXist-db/documentation#108] opened 2017-04-10 19:39 UTC
Hello, the demo page at the bottom of http://exist-db.org/exist/apps/demo/examples/templating/templates.html?n1=2&n2=8 (i.e. http://exist-db.org/exist/restxq/page?user=Sam&language=it) returns a 

    HTTP ERROR 405
    Problem accessing /exist/restxq/page. Reason:
    HTTP method GET is not supported by this URL

error.

**Comment by joewiz** [comment] 2017-04-10 20:57
@lguariento Thanks for the report! It appears the exist-db.org website is out of date. The app works fine on my local machine, running eXist 3.1.1: http://localhost:8080/exist/restxq/page?user=Sam&language=it:

> ![screen shot 2017-04-10 at 4 53 31 pm](https://cloud.githubusercontent.com/assets/59118/24882210/43275f58-1e0e-11e7-8117-ed3362a95f07.png)

@eXist-db/core The problem of exist-db.org being out of date has been on the agenda of the community call for several weeks. Please see this issue for an example. Let's discuss an action plan on the next developer-oriented call.

**Comment by joewiz** [comment] 2017-04-10 20:58
Perhaps we'd best keep this issue open until the server is up to date and the problem is fixed on the server. Maybe we need an `exist-db.org` repo in which to track such issues?

**Comment by lguariento** [comment] 2017-04-10 21:11
Let me know if you need help with anything, happy to help (I'm loving eXist-db)!

**Comment by joewiz** [comment] 2017-04-10 21:29
@lguariento Thanks, that's great to hear! Yes, the documentation on the server is also behind what you would see on your own eXist system if you install the latest release of eXist and the documentation app. Hopefully this will be addressed soon. I'd encourage you to install the documentation locally, and then if you spot anything that still needs improvement, let us know here via an issue or a pull request.

**Comment by lguariento** [comment] 2017-04-10 22:14
Will do, thanks.

**Comment by duncdrum** [comment] 2017-12-19 14:09
problem is fixed on the exist-db.org website, should it break again we can report it on the demo's repo https://github.com/eXist-db/demo-apps

**Closed by duncdrum** 2017-12-19 14:09 UTC
Labels: broken-links
